name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-buildx-action@v3

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./Ecommerce-Backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:latest

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-buildx-action@v3

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Ecommerce-Frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-frontend:latest
          build-args: |
            VITE_API_BASE_URL=/api